
from django.core import exceptions


class ScopeException(exceptions.ValidationError):
    pass